-- 00002_pairing.sql
-- Device pairing (ADR-006) via a code generated by the first phone. RLS filters
-- by membership, so a new device could NOT insert itself into someone else's
-- household on its own (chicken-and-egg). These SECURITY DEFINER functions
-- encapsulate the only privileged operation, while remaining callable via
-- supabase.rpc() with the device's (anonymous) JWT.

-- ------------------------------------------------------------
-- Align the week_start_day constraint with the client convention
-- (DateTime.weekday: 1 = Monday … 7 = Sunday). The initial schema used
-- 0..6, incompatible with the values the app writes today.
-- ------------------------------------------------------------
ALTER TABLE household DROP CONSTRAINT IF EXISTS household_week_start_day_check;
ALTER TABLE household
    ADD CONSTRAINT household_week_start_day_check CHECK (week_start_day BETWEEN 1 AND 7);
ALTER TABLE household ALTER COLUMN week_start_day SET DEFAULT 1;

-- ------------------------------------------------------------
-- create_pairing_code: called by the "inviting" device. Derives its household
-- from the membership and generates a 6-digit code valid for 10 minutes.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION create_pairing_code()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_device    UUID := auth.uid();
    v_household UUID;
    v_code      TEXT;
BEGIN
    IF v_device IS NULL THEN
        RAISE EXCEPTION 'not_authenticated';
    END IF;

    SELECT household_id INTO v_household
    FROM membership
    WHERE device_id = v_device
    LIMIT 1;

    IF v_household IS NULL THEN
        RAISE EXCEPTION 'no_household';
    END IF;

    -- 6-digit code; retry on a collision against the UNIQUE index.
    LOOP
        v_code := lpad((floor(random() * 1000000))::INT::TEXT, 6, '0');
        BEGIN
            INSERT INTO pairing_code (id, household_id, code, expires_at, consumed, created_at)
            VALUES (gen_random_uuid(), v_household, v_code,
                    now() + INTERVAL '10 minutes', FALSE, now());
            EXIT;
        EXCEPTION WHEN unique_violation THEN
            -- retry with another code
        END;
    END LOOP;

    RETURN v_code;
END;
$$;

-- ------------------------------------------------------------
-- redeem_pairing_code: called by the second device. Validates the code and
-- joins the inviter's household ("adopts A"): the device's own memberships and
-- empty households are removed, so it stays a member of a single household. If
-- the device already has its own data it blocks, to avoid orphaning it.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION redeem_pairing_code(p_code TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_device    UUID := auth.uid();
    v_household UUID;
    v_old       RECORD;
BEGIN
    IF v_device IS NULL THEN
        RAISE EXCEPTION 'not_authenticated';
    END IF;

    SELECT household_id INTO v_household
    FROM pairing_code
    WHERE code = p_code
      AND consumed = FALSE
      AND expires_at > now()
    FOR UPDATE;

    IF v_household IS NULL THEN
        RAISE EXCEPTION 'invalid_or_expired_code';
    END IF;

    -- Already a member: idempotent operation.
    IF EXISTS (SELECT 1 FROM membership
               WHERE device_id = v_device AND household_id = v_household) THEN
        UPDATE pairing_code SET consumed = TRUE WHERE code = p_code;
        RETURN v_household;
    END IF;

    -- Block if the device already owns its own data (joining another household
    -- would orphan it).
    IF EXISTS (
        SELECT 1 FROM membership m
        WHERE m.device_id = v_device
          AND (
              EXISTS (SELECT 1 FROM dish        d WHERE d.household_id = m.household_id) OR
              EXISTS (SELECT 1 FROM ingredient  i WHERE i.household_id = m.household_id) OR
              EXISTS (SELECT 1 FROM tag         t WHERE t.household_id = m.household_id) OR
              EXISTS (SELECT 1 FROM week_plan   w WHERE w.household_id = m.household_id)
          )
    ) THEN
        RAISE EXCEPTION 'device_has_data';
    END IF;

    -- Remove the device's memberships and any households left without members
    -- (its empty bootstrap households).
    FOR v_old IN SELECT household_id FROM membership WHERE device_id = v_device LOOP
        DELETE FROM membership
        WHERE device_id = v_device AND household_id = v_old.household_id;
        IF NOT EXISTS (SELECT 1 FROM membership WHERE household_id = v_old.household_id) THEN
            DELETE FROM household WHERE id = v_old.household_id;
        END IF;
    END LOOP;

    INSERT INTO membership (id, household_id, device_id, role, joined_at, updated_at)
    VALUES (gen_random_uuid(), v_household, v_device, 'member', now(), now());

    UPDATE pairing_code SET consumed = TRUE WHERE code = p_code;

    RETURN v_household;
END;
$$;

GRANT EXECUTE ON FUNCTION create_pairing_code() TO authenticated;
GRANT EXECUTE ON FUNCTION redeem_pairing_code(TEXT) TO authenticated;
